Extend test coverage of QuickMenu classes
domhanak/kie-wb-common pull request #2
Opened 2018-03-21 12:17 UTC by domhanak

Add one test to cover build method of MenuUtils.
Add classes to cover Builders.

2018-03-22 07:58 UTC, hasys commented
Hi @domhanak,

1. Please set up you IDE according to KIE Group rules (instruction can be found there: https://github.com/kiegroup/droolsjbpm-build-bootstrap#developing-with-intellij), to test locally use `mvn clean package -Dfull`, especially:
  * IDE formatter, 
  * imports,
  * License Header
2. There are failing test:

```
Results :

Failed tests: 
  ShapeSetsMenuItemBuilderTest.testBuild:73 
shapeSet.getDescription();
Wanted 1 time:
-> at org.kie.workbench.common.stunner.client.widgets.menu.dev.ShapeSetsMenuItemBuilderTest.testBuild(ShapeSetsMenuItemBuilderTest.java:73)
But was 2 times. Undesired invocation:
-> at org.kie.workbench.common.stunner.client.widgets.menu.dev.ShapeSetsMenuItemsBuilder$2.<init>(ShapeSetsMenuItemsBuilder.java:65)


Tests run: 148, Failures: 1, Errors: 0, Skipped: 0
```

2018-03-22 08:14 UTC, domhanak commented
Now the tests fails and I am not sure if it is a valid tests or I do have a bad check there.
java.lang.AssertionError: 
Expecting:
 <"org.kie.workbench.common.stunner.client.widgets.menu.MenuUtils$1$1#null">
to contain:
 <"Test ID">

2018-03-23 08:45 UTC, jhrcek requested changes
Some feedback inline..

2018-03-23 08:45 UTC, jhrcek commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/menu/MenuUtilsTest.java
> +        assertEquals(false, hasEnabledIsWidget.isEnabled());
`assertEquals(false, ..` -> `assertFalse`

Better yet use AssertJ consistently in the whole PR.

2018-03-23 08:45 UTC, jhrcek commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/menu/MenuUtilsTest.java
> +        when(hasEnabledIsWidget.isEnabled()).thenReturn(true);
This mocking doesn't make sense (or the following assert is useless) - you're basically testing, that mockito mocked the call to `isEnabled()`correctly? But hasEnabledIsWidget isn't a mock, or is it?

2018-03-23 08:45 UTC, jhrcek commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/menu/MenuUtilsTest.java
> +        assertEquals(true, hasEnabledIsWidget.isEnabled());
assertTrue

2018-03-23 08:45 UTC, jhrcek commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/menu/dev/ShapeSetsMenuItemBuilderTest.java
> +        Assertions.assertThat(menuItem).isNotNull();
Please static import Assertions to avoid some boilerplate.

2018-03-23 08:45 UTC, jhrcek commented on kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/menu/dev/MenuDevCommandBuilderTest.java
> +    @Mock
Doesn't make sense to annotate this with `@Mock` if you're creating your own instance in the `setUp()`

2018-05-23 09:42 UTC, closed without merging